# Generated by Django 2.2.5 on 2021-04-19 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acomodacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='número')),
                ('tamanho', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=70)),
                ('telefone', models.CharField(max_length=11)),
                ('vip', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Oferecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.IntegerField()),
                ('nome', models.CharField(max_length=70)),
                ('endereco', models.CharField(max_length=70, verbose_name='endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=70)),
                ('descricao', models.CharField(max_length=400, verbose_name='descrição')),
                ('duracao_media', models.DurationField(verbose_name='duração média')),
                ('unidades', models.ManyToManyField(through='sistema_pet_shop.Oferecimento', to='sistema_pet_shop.Unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='número')),
                ('equipamentos', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Unidade')),
=======
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.unidade')),
>>>>>>> 8db331b66cd3134abbb693bb05e95c4e03aca762
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('especie', models.CharField(max_length=70, verbose_name='espécie')),
                ('raca', models.CharField(max_length=20, verbose_name='raça')),
                ('sexo', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='oferecimento',
            name='servico',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Servico'),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.servico'),
>>>>>>> 8db331b66cd3134abbb693bb05e95c4e03aca762
        ),
        migrations.AddField(
            model_name='oferecimento',
            name='unidade',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Unidade'),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.unidade'),
>>>>>>> 8db331b66cd3134abbb693bb05e95c4e03aca762
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.IntegerField()),
                ('nome', models.CharField(max_length=70)),
                ('cargo', models.CharField(max_length=70)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salário')),
<<<<<<< HEAD
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Unidade')),
=======
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.unidade')),
>>>>>>> 8db331b66cd3134abbb693bb05e95c4e03aca762
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('aplicacao', models.CharField(max_length=200, verbose_name='aplicação')),
                ('quantidade', models.IntegerField()),
<<<<<<< HEAD
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Unidade')),
=======
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.unidade')),
>>>>>>> 8db331b66cd3134abbb693bb05e95c4e03aca762
            ],
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
<<<<<<< HEAD
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Acomodacao')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Pet')),
=======
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.acomodacao')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.pet')),
>>>>>>> 8db331b66cd3134abbb693bb05e95c4e03aca762
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='unidades',
            field=models.ManyToManyField(through='sistema_pet_shop.Cadastro', to='sistema_pet_shop.Unidade'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='cliente',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Cliente'),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.cliente'),
>>>>>>> 8db331b66cd3134abbb693bb05e95c4e03aca762
        ),
        migrations.AddField(
            model_name='cadastro',
            name='unidade',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Unidade'),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.unidade'),
>>>>>>> 8db331b66cd3134abbb693bb05e95c4e03aca762
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
<<<<<<< HEAD
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Funcionario')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Pet')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Sala')),
=======
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.funcionario')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.pet')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.sala')),
>>>>>>> 8db331b66cd3134abbb693bb05e95c4e03aca762
            ],
        ),
        migrations.AddField(
            model_name='acomodacao',
            name='unidade',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.Unidade'),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pet_shop.unidade'),
>>>>>>> 8db331b66cd3134abbb693bb05e95c4e03aca762
        ),
    ]
