# Generated by Django 3.2 on 2021-04-20 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pet_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estoque',
            new_name='Produto',
        ),
    ]
