# Generated by Django 3.1.7 on 2021-04-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pet_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='cep',
            field=models.IntegerField(),
        ),
    ]
