from django.urls import path
from . import views

app_name = "sistema_pet_shop"

urlpatterns = [
    path('', views.Unidades.as_view(), name="unidades"),
    path('detail-unidade/<int:pk>', views.DetailUnidade.as_view(), name="detail-unidade"),
    path('nova-unidade', views.novaUnidade, name="nova-unidade"),
    path('editar-unidade/<int:pk>', views.editUnidade, name="nova-unidade"),
    path('delete-unidade/<int:pk>', views.deleteUnidade, name='delete-unidade'),
    path('clientes', views.Clientes.as_view(), name="clientes"),
    path('detail-cliente/<int:pk>', views.DetailCliente.as_view(), name="detail-cliente"),
    path('novo-cliente', views.novoCliente, name="novo-cliente"),
    path('editar-cliente/<int:pk>', views.editCliente, name="novo-cliente"),
    path('delete-cliente/<int:pk>', views.deleteCliente, name='delete-cliente'),
    path('detail-pet/<int:pk>', views.DetailPet.as_view(), name="detail-pet"),
    path('novo-pet/<int:pk>', views.novoPet, name="novo-pet"),
    path('editar-pet/<int:pk>', views.editPet, name="novo-pet"),
    path('delete-pet/<int:pk>', views.deletePet, name='delete-pet'),
    path('funcionarios/<int:pk>', views.Funcionarios.as_view(), name="funcionarios"),
    path('detail-funcionario/<int:pk>', views.DetailFuncionario.as_view(), name="detail-funcionario"),
    path('novo-funcionario/<int:pk>', views.novoFuncionario, name="novo-funcionario"),
    path('editar-funcionario/<int:pk>', views.editFuncionario, name="novo-funcionario"),
    path('delete-funcionario/<int:pk>', views.deleteFuncionario, name='delete-funcionario'),
    path('novo-servico/', views.novoServico, name="novo-servico"),
    path('servicos/', views.Servicos.as_view(), name="servicos"),
    #path('servicos/<int:pk>', views.Servicos.as_view(), name="servicos"),
    path('editar-servico/<int:pk>', views.editServico, name="novo-servico"),
    path('delete-servico/<int:pk>', views.deleteServico, name='delete-servico'),
    path('nova-acomodacao/<int:pk>', views.novaAcomodacao, name="nova-acomodacao"),
    path('acomodacoes/<int:pk>', views.Acomodacoes.as_view(), name="acomodacoes"),
    path('editar-acomodacao/<int:pk>', views.editAcomodacao, name="nova-acomodacao"),
    path('delete-acomodacao/<int:pk>', views.deleteAcomodacao, name='delete-acomodacao'),
    path('nova-sala/<int:pk>', views.novaSala, name="nova-sala"),
    path('salas/<int:pk>', views.Salas.as_view(), name="salas"),
    path('editar-sala/<int:pk>', views.editSala, name="editar-sala"),
    path('delete-sala/<int:pk>', views.deleteSala, name='delete-sala'),
    path('novo-agendamento/<int:pk>', views.novoAgendamento, name="novo-agendamento"),
    path('editar-agendamento/<int:pk>', views.editAgendamento, name="novo-agendamento"),
    path('delete-agendamento/<int:pk>', views.deleteAgendamento, name='delete-agendamento'),
    path('nova-estadia/<int:pk>', views.novaEstadia, name="nova-estadia"),
    path('editar-estadia/<int:pk>', views.editEstadia, name="nova-estadia"),
    path('delete-estadia/<int:pk>', views.deleteEstadia, name='delete-estadia'),  
    path('estoque/<int:pk>', views.Estoque.as_view(), name="estoque"),
    path('novo-produto/<int:pk>', views.novoProduto, name="novo-produto"),
    path('editar-produto/<int:pk>', views.editProduto, name="editar-produto"),
    path('delete-produto/<int:pk>', views.deleteProduto, name='delete-produto'),
    
]   
